---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: golang:1.13
  commands:
    - "go build -o ./myapp"

- name: docker-build
  image: plugins/docker
  privileged: true
  settings:
    dockerfile: Dockerfile
    debug: true
    repo: registry:5000/conekta/go-ci
    registry: registry:5000
    cache_from: golang:1.13
    autotag: no
    insecure: true
    tags:
      - latest
      - main
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_BUILDKIT: 0
    PLUGIN_DRY_RUN: "false"
    PLUGIN_PURGE: "false"
  depends_on:
    - "build"

- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a

- name: runapp
#  image: registry:5000/conekta/go-ci:main
  image: docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
#  settings:
#    insecure: true
#    registry: registry:5000
#    repo: registry:5000/conekta/go-ci
  depends_on:
    - "docker-build"
  commands:
  - sleep 10
  - ls / 
  - docker ps -a
  - docker run -d registry:5000/conekta/go-ci:main
  - docker ps -a

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
- name: registry
  image: registry
  settings:
    insecure: true
    

volumes:
- name: dockersock
  temp: {}
