kind: pipeline
type: kubernetes
# resource requests are defined on the pipeline level
resources:
  requests:
    cpu: 8000
    memory: 30GiB
steps:
  - name: en
    image: alpine
    commands:
      - echo hello
    resources:
      # resource limits are defined for each step
      limits:
        cpu: 6000
        memory: 24GiB

  - name: es
    image: alpine
    commands:
      - echo hola

  - name: fr
    image: alpine
    commands:
      - echo bonjour
      - cat /proc/cpuinfo
      - free
