kind: pipeline
type: kubernetes
name: default
#resources:
#  requests:
#    cpu: 8000
#    memory: 32000MiB
steps:
- name: test
  image: alpine
  commands:
  - free
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - head random.txt
