kind: pipeline
type: kubernetes
# resource requests are defined on the pipeline level
resources:
  requests:
    cpu: 8000
    memory: 30GiB
steps:
  - name: en
    image: alpine
    commands:
      - echo hello

  - name: es
    image: alpine
    commands:
      - echo hola

  - name: fr
    image: alpine
    commands:
      - echo bonjour
      - cat /proc/cpuinfo
      - free
